config = {
    "GOOGLE_MAPS_API_KEY": "YOUR_GOOGLE_MAPS_API_KEY_HERE",
    "HUGGING_FACE_API_KEY": "YOUR_HUGGING_FACE_API_KEY_HERE",
    "OPENAI_API_KEY": OPENAI_API_KEY,
    "FIREBASE_CONFIG": FIREBASE_CONFIG,
    "DEBUG": DEBUG,
    "SECRET_KEY": SECRET_KEY
} 